// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Post struct {
	Slug      string `json:"slug"`
	Titulo    string `json:"titulo"`
	Resumen   string `json:"resumen"`
	Contenido string `json:"contenido"`
	Publicado string `json:"publicado"`
}
