// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const countPosts = `-- name: CountPosts :one
SELECT count(*) FROM posts
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (slug, titulo, resumen, contenido, publicado)
VALUES (?, ?, ?, ?, ?)
`

type CreatePostParams struct {
	Slug      string `json:"slug"`
	Titulo    string `json:"titulo"`
	Resumen   string `json:"resumen"`
	Contenido string `json:"contenido"`
	Publicado string `json:"publicado"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.Slug,
		arg.Titulo,
		arg.Resumen,
		arg.Contenido,
		arg.Publicado,
	)
	return err
}

const getPost = `-- name: GetPost :one
SELECT slug, titulo, resumen, contenido, publicado
FROM posts
WHERE slug = ?
`

func (q *Queries) GetPost(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, slug)
	var i Post
	err := row.Scan(
		&i.Slug,
		&i.Titulo,
		&i.Resumen,
		&i.Contenido,
		&i.Publicado,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT slug, titulo, resumen, contenido, publicado
FROM posts
ORDER BY publicado DESC
`

func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.Slug,
			&i.Titulo,
			&i.Resumen,
			&i.Contenido,
			&i.Publicado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
