// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Contacto struct {
	ID      int64  `json:"id"`
	Nombre  string `json:"nombre"`
	Email   string `json:"email"`
	Mensaje string `json:"mensaje"`
	Creado  string `json:"creado"`
}
