// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createContacto = `-- name: CreateContacto :exec
INSERT INTO contactos (nombre, email, mensaje)
VALUES (?, ?, ?)
`

type CreateContactoParams struct {
	Nombre  string `json:"nombre"`
	Email   string `json:"email"`
	Mensaje string `json:"mensaje"`
}

func (q *Queries) CreateContacto(ctx context.Context, arg CreateContactoParams) error {
	_, err := q.db.ExecContext(ctx, createContacto, arg.Nombre, arg.Email, arg.Mensaje)
	return err
}
