// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Producto struct {
	Slug        string `json:"slug"`
	Titulo      string `json:"titulo"`
	Descripcion string `json:"descripcion"`
	Precio      int64  `json:"precio"`
}
