// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const countProductos = `-- name: CountProductos :one
SELECT count(*) FROM productos
`

func (q *Queries) CountProductos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProducto = `-- name: CreateProducto :exec
INSERT INTO productos (slug, titulo, descripcion, precio)
VALUES (?, ?, ?, ?)
`

type CreateProductoParams struct {
	Slug        string `json:"slug"`
	Titulo      string `json:"titulo"`
	Descripcion string `json:"descripcion"`
	Precio      int64  `json:"precio"`
}

func (q *Queries) CreateProducto(ctx context.Context, arg CreateProductoParams) error {
	_, err := q.db.ExecContext(ctx, createProducto,
		arg.Slug,
		arg.Titulo,
		arg.Descripcion,
		arg.Precio,
	)
	return err
}

const getProducto = `-- name: GetProducto :one
SELECT slug, titulo, descripcion, precio
FROM productos
WHERE slug = ?
`

func (q *Queries) GetProducto(ctx context.Context, slug string) (Producto, error) {
	row := q.db.QueryRowContext(ctx, getProducto, slug)
	var i Producto
	err := row.Scan(
		&i.Slug,
		&i.Titulo,
		&i.Descripcion,
		&i.Precio,
	)
	return i, err
}

const listProductos = `-- name: ListProductos :many
SELECT slug, titulo, descripcion, precio
FROM productos
ORDER BY titulo
`

func (q *Queries) ListProductos(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listProductos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Producto{}
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.Slug,
			&i.Titulo,
			&i.Descripcion,
			&i.Precio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
