// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const countUsuarios = `-- name: CountUsuarios :one
SELECT count(*) FROM usuarios
`

func (q *Queries) CountUsuarios(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsuarios)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUsuario = `-- name: CreateUsuario :exec
INSERT INTO usuarios (email, password_hash) VALUES (?, ?)
`

type CreateUsuarioParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) error {
	_, err := q.db.ExecContext(ctx, createUsuario, arg.Email, arg.PasswordHash)
	return err
}

const getUsuario = `-- name: GetUsuario :one
SELECT id, email, password_hash, creado FROM usuarios WHERE id = ?
`

func (q *Queries) GetUsuario(ctx context.Context, id int64) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Creado,
	)
	return i, err
}

const getUsuarioByEmail = `-- name: GetUsuarioByEmail :one
SELECT id, email, password_hash, creado FROM usuarios WHERE email = ?
`

func (q *Queries) GetUsuarioByEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuarioByEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Creado,
	)
	return i, err
}
